image: node:current-alpine3.15

stages:
  - test
  - deploy

test:
  stage: test
  script:
  - mkdir website
  - mv blog website/.
  - mv docs website/.
  - mv src website/.
  - mv static website/.
  - mv babel.config.js website/.
  - mv docusaurus.config.js website/.
  - mv package.json website/.
  - mv sidebars.js website/.
  - mv yarn.lock website/.
  - cd website
  - yarn install
  - yarn build
  except:
    - main

pages:
  stage: deploy
  script:
  - mkdir website
  - mv blog website/.
  - mv docs website/.
  - mv src website/.
  - mv static website/.
  - mv babel.config.js website/.
  - mv docusaurus.config.js website/.
  - mv package.json website/.
  - mv sidebars.js website/.
  - mv yarn.lock website/.
  - cd website
  - yarn install
  - yarn build
  - mv ./build ../public
  artifacts:
    paths:
    - public
  only:
    - main
  environment:
    name: energi-wiki
    url: https://zalam003.gitlab.io
